version: '3.8'
services:
    session:
        container_name: session
        build:
            context: SESSION
            dockerfile: docker/Dockerfile
        environment:
            - spring.r2dbc.url=r2dbc:postgresql://database:5432/wordledb
        volumes:
            - gradlewrapper:/root/.gradle/wrapper:rw
        ports:
            - 7777:8080
        depends_on:
            - database
    frontend:
        container_name: frontend
        build:
            context: FE
            dockerfile: Dockerfile
        ports:
            - 80:80
        depends_on:
            - authorization
            - session
    database:
        container_name: database
        build:
            context: DATABASE
            dockerfile: dockerfile
        command: ["postgres", "-c", "log_statement=all"]
        ports:
            - 5432:5432
    authorization:
        container_name: authorization
        build:
            context: AUTHORIZATION
            dockerfile: docker/Dockerfile
        environment:
            - spring.r2dbc.url=r2dbc:postgresql://database:5432/wordledb
        volumes:
            - gradlewrapper:/root/.gradle/wrapper:rw
        ports:
            - 7788:8080
        depends_on:
            - database
volumes:
    gradlewrapper:
