version: '3.8'
services:
    session:
        container_name: session
        build:
            context: SESSION
            dockerfile: docker/Dockerfile
        volumes:
            - gradlewrapper:/root/.gradle/wrapper:rw
        ports:
            - 7777:8080
    frontend:
        container_name: frontend
        build:
            context: FE
            dockerfile: Dockerfile
        ports:
            - 80:80
    database:
        container_name: database
        build:
            context: DATABASE
            dockerfile: dockerfile
        ports:
            - 5432:5432
volumes:
    gradlewrapper:
